import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST(request: Request) {
  try {
    const { email, password, name } = await request.json();

    if (!email || !password) {
      return NextResponse.json({ error: 'Email and password are required' }, { status: 400 });
    }

    // Generate link using Admin API (creates the user but prevents Supabase from sending its default email)
    const { data: linkData, error: linkError } = await supabaseAdmin.auth.admin.generateLink({
      type: 'signup',
      email,
      password,
      data: { full_name: name || '' }
    });

    if (linkError) {
      return NextResponse.json({ error: linkError.message }, { status: 400 });
    }

    // We use the action_link generated by Supabase because it properly verifies the token
    // on the Supabase backend and then redirects to the callback route with the necessary session info.
    let confirmUrl = linkData.properties.action_link;

    // Ensure the redirect_to parameter points to our callback
    const urlObj = new URL(confirmUrl);
    urlObj.searchParams.set('redirect_to', `${process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'}/callback`);
    confirmUrl = urlObj.toString();

    const { data, error } = await resend.emails.send({
      from: 'Sva-Rajya <onboarding@resend.dev>', // Update with your verified Resend domain if necessary
      to: email,
      subject: 'Verify your email for Sva-Rajya',
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <h2>Welcome to Sva-Rajya!</h2>
          <p>Hi ${name || 'there'},</p>
          <p>Please confirm your email address by clicking the link below so you can access your account.</p>
          <div style="margin: 30px 0;">
            <a href="${confirmUrl}" style="background-color: #fbbf24; color: #000; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">Confirm Email</a>
          </div>
          <p>If you did not request this, please ignore this email.</p>
        </div>
      `
    });

    if (error) {
      return NextResponse.json({ error }, { status: 400 });
    }

    return NextResponse.json({ success: true, user: linkData.user });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
