import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST(request: Request) {
  try {
    const { email } = await request.json();

    if (!email) {
      return NextResponse.json({ error: 'Email is required' }, { status: 400 });
    }

    const { data: linkData, error: linkError } = await supabaseAdmin.auth.admin.generateLink({
      type: 'recovery',
      email,
    });

    if (linkError) {
      return NextResponse.json({ error: linkError.message }, { status: 400 });
    }

    // We use the action_link generated by Supabase.
    // When the user clicks this, Supabase verifies the recovery token and generates
    // the true JWT access_token, then redirects to the callback route:
    let resetUrl = linkData.properties.action_link;

    const urlObj = new URL(resetUrl);
    urlObj.searchParams.set('redirect_to', `${process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'}/callback`);
    resetUrl = urlObj.toString();

    const { data, error } = await resend.emails.send({
      from: 'Sva-Rajya <security@resend.dev>', // Update with your verified Resend domain if necessary
      to: email,
      subject: 'Reset your password for Sva-Rajya',
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <h2>Password Reset Request</h2>
          <p>We received a request to reset your password. Click the link below to set a new password:</p>
          <div style="margin: 30px 0;">
            <a href="${resetUrl}" style="background-color: #fbbf24; color: #000; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">Reset Password</a>
          </div>
          <p>If you did not request this, you can safely ignore this email.</p>
        </div>
      `
    });

    if (error) {
      return NextResponse.json({ error }, { status: 400 });
    }

    return NextResponse.json({ success: true, data });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
